image: docker:latest

stages:
 - prepare-image
 - prepare-tree
 - build

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

services:
  - docker:dind
before_script:
  - apk --update add make cmake py-pip git
  - pip install docker-compose

nightly-prepare-image:
  stage: prepare-image
  script:
   - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
   - docker build --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA .
   - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
  except:
   - tags

nightly-prepare-tree:
  stage: prepare-tree
  script:
    - mkdir -p opt/xcsoar opt/xcsoar-ccache
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-update
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar
      - opt/xcsoar-ccache

nightly-unix:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-compile-unix
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/UNIX

nightly-android:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-compile-android
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/ANDROID

nightly-pc:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-compile-pc
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/PC

nightly-kobo:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-compile-kobo
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/KOBO

nightly-docs:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache $CONTAINER_IMAGE:$CI_COMMIT_SHA xcsoar-compile-manuals
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output
